# Generated by Django 3.0.6 on 2020-09-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.user')),
            ],
        ),
    ]
