# Generated by Django 3.0.7 on 2020-10-21 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batch_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='batch_ticket',
            fields=[
                ('batch_ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('availability_status', models.CharField(max_length=20)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.batch')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('emp_det_id', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('primary_phone', models.CharField(max_length=10, unique=True)),
                ('secondary_phone', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Employee', 'Employee')], default='Employee', max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('qualification', models.CharField(max_length=500)),
                ('trained_years', models.IntegerField(default=0)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('permenent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('joined_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('eq_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0, max_length=5)),
                ('qty', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='equipment_event',
            fields=[
                ('eq_ev_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('budget', models.FloatField(max_length=5)),
                ('email_address', models.CharField(max_length=50)),
                ('occassion_type', models.CharField(max_length=10)),
                ('time', models.TimeField(auto_now=True)),
                ('head_count', models.IntegerField(max_length=10)),
                ('creator_phone', models.CharField(max_length=10)),
                ('schedule_file', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('event_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=100)),
                ('event_creator_name', models.CharField(max_length=20)),
                ('created_month', models.CharField(default='October', max_length=5)),
                ('created_date', models.CharField(default=datetime.datetime(2020, 10, 21, 22, 24, 14, 561635), max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('pay_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pay_type', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0, max_length=5)),
                ('order_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=32, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('createdDate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.user')),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='inventory_items',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.equipment_event')),
                ('image', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='rented_item',
            fields=[
                ('rented_item_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.equipment')),
                ('supplier', models.CharField(max_length=50)),
                ('rented_date', models.DateField(auto_now=True)),
                ('rental_period', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tkt_name', models.CharField(max_length=50)),
                ('tkt_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0, max_length=5)),
                ('expiration_date', models.DateField()),
                ('image', models.CharField(max_length=500)),
                ('no_of_tickets', models.IntegerField(max_length=5)),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('sal_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('basic_sal', models.IntegerField(default=0)),
                ('extra_hours', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('Year', models.IntegerField(default='2021', max_length=4)),
                ('paid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Paid_Date', models.DateField(blank=True, null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.department')),
                ('emp_det_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('reservation_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('batch_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.batch_ticket')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='rent_details',
            fields=[
                ('rent_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rental_date', models.DateField(auto_now=True)),
                ('rental_period', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField()),
                ('eq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.equipment')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.reservation'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feed_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('ratings', models.IntegerField(max_length=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.user'),
        ),
        migrations.AddField(
            model_name='equipment_event',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event'),
        ),
        migrations.CreateModel(
            name='emp_details_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='dept_manager_name',
            field=models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
        migrations.AddField(
            model_name='batch',
            name='ticket_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_management.ticket'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer'),
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('pack_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('pack_name', models.CharField(max_length=50)),
                ('featuers', models.CharField(max_length=500)),
                ('pack_type', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('inv_status', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.payment')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin'),
        ),
        migrations.AddField(
            model_name='emp_details',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin'),
        ),
        migrations.CreateModel(
            name='dept_supervisor',
            fields=[
                ('emp_id', models.OneToOneField(limit_choices_to={'position': 'Supervisor'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.department')),
            ],
        ),
        migrations.CreateModel(
            name='dept_manager',
            fields=[
                ('emp_id', models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.department')),
            ],
        ),
        migrations.CreateModel(
            name='dept_employee',
            fields=[
                ('emp_id', models.OneToOneField(limit_choices_to={'position': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin'),
        ),
        migrations.AddField(
            model_name='batch_ticket',
            name='cus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_management.customer'),
        ),
        migrations.CreateModel(
            name='advertistment',
            fields=[
                ('ad_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('ad_type', models.CharField(max_length=30)),
                ('ad_title', models.CharField(max_length=50)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
                ('pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.package')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.payment')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='customer_equipment',
            fields=[
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.customer')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.equipment')),
            ],
        ),
    ]
