# Generated by Django 3.0.7 on 2020-10-21 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2020, 10, 21, 22, 24, 40, 910642), max_length=20),
        ),
    ]
