# Generated by Django 3.1 on 2020-10-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equip_rental',
            fields=[
                ('rent_equipment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='null', max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.equipment')),
            ],
        ),
    ]
