# Generated by Django 3.0.6 on 2020-09-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feed_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('ratings', models.IntegerField(max_length=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.user')),
            ],
        ),
    ]
