# Generated by Django 3.1 on 2020-10-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_equip_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_details',
            name='pay_id',
        ),
    ]
