# Generated by Django 3.0.6 on 2020-09-06 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_customer_event_package_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batch_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('qty', models.IntegerField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='batch_ticket',
            fields=[
                ('batch_ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('availability_status', models.CharField(max_length=20)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.batch')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('reservation_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('batch_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.batch_ticket')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('pay_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pay_type', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0, max_length=5)),
                ('order_type', models.CharField(max_length=50)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='advertistment',
            fields=[
                ('ad_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('ad_type', models.CharField(max_length=30)),
                ('ad_title', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.customer')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
                ('pack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.package')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.payment')),
            ],
        ),
    ]
