# Generated by Django 3.0.6 on 2020-09-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_advertistment_batch_batch_ticket_payment_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('eq_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0, max_length=5)),
                ('qty', models.IntegerField(max_length=5)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
            ],
        ),
        migrations.CreateModel(
            name='rented_event',
            fields=[
                ('rented_item_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.equipment')),
                ('supplier', models.CharField(max_length=50)),
                ('rented_date', models.DateField(auto_now=True)),
                ('rental_period', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('inv_status', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.payment')),
            ],
        ),
        migrations.CreateModel(
            name='equipment_event',
            fields=[
                ('eq_ev_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField(max_length=5)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
            ],
        ),
    ]
