# Generated by Django 3.0.6 on 2020-09-06 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_equipment_equipment_event_invoice_rented_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_equipment',
            fields=[
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.customer')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='rented_item',
            fields=[
                ('rented_item_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.equipment')),
                ('supplier', models.CharField(max_length=50)),
                ('rented_date', models.DateField(auto_now=True)),
                ('rental_period', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='rented_event',
        ),
    ]
