# Generated by Django 3.0.6 on 2020-09-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_auto_20200906_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_items',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.equipment_event')),
                ('image', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('leave_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=50)),
                ('leave_type', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('paid', models.CharField(max_length=10)),
                ('total_payment', models.FloatField(default=0.0)),
                ('employee_name', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('emp_det_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('primary_phone', models.CharField(max_length=10)),
                ('secondary_phone', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=30)),
                ('trained', models.CharField(max_length=10)),
                ('joined_date', models.DateField(auto_now=True)),
                ('permenent', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('trained_year', models.IntegerField(max_length=5)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
            ],
        ),
        migrations.CreateModel(
            name='emp_details_leave',
            fields=[
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.leave')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details')),
            ],
        ),
    ]
