# Generated by Django 3.0.6 on 2020-09-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_emp_details_emp_details_leave_inventory_items_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_manager_name', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.admin')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('sal_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=10)),
                ('basic_sal', models.FloatField(default=0.0)),
                ('extra_hours', models.IntegerField(default=0)),
                ('extra_payment', models.FloatField(default=0.0)),
                ('paid_date', models.DateField()),
                ('paid', models.CharField(max_length=5)),
                ('total_payment', models.FloatField(default=0.0)),
                ('employee_name', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=50)),
                ('no_of_leaves', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dept_supervisor',
            fields=[
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.department')),
            ],
        ),
        migrations.CreateModel(
            name='dept_manager',
            fields=[
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.department')),
            ],
        ),
        migrations.CreateModel(
            name='dept_employee',
            fields=[
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.department')),
            ],
        ),
    ]
