# Generated by Django 3.0.7 on 2020-09-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_department_dept_employee_dept_manager_dept_supervisor_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='no_of_leaves',
            new_name='bonus',
        ),
        migrations.RemoveField(
            model_name='dept_supervisor',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='emp_details',
            name='trained_year',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='total_payment',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='extra_payment',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='total_payment',
        ),
        migrations.AddField(
            model_name='dept_supervisor',
            name='emp_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AddField(
            model_name='emp_details',
            name='trained_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='dept_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='event_management.department'),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='event_management.emp_details'),
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='Paid_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='dept_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='event_management.department'),
        ),
        migrations.AddField(
            model_name='salary',
            name='emp_det_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='event_management.emp_details'),
        ),
        migrations.AddField(
            model_name='salary',
            name='year',
            field=models.IntegerField(default='2021', max_length=4),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_manager_name',
            field=models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.DO_NOTHING, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dept_employee',
            name='emp_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_employee',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dept_manager',
            name='emp_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_manager',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dept_supervisor',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='emp_det_id',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='permenent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='position',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Employee', 'Employee')], default='Employee', max_length=15),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='primary_phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='secondary_phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='trained',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Non-Paid', 'Non-Paid')], default='Non-Paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'december')], default='January', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='year',
            field=models.CharField(default=2021, max_length=4),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_sal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'december')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='paid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='sal_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
