# Generated by Django 3.0.7 on 2020-10-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_auto_20200907_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='trained',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='leave',
            name='emp_det_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.user'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_manager_name',
            field=models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_employee',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_manager',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_supervisor',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Supervisor'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='permenent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='leave',
            name='dept_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.department'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='dept_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.department'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='emp_det_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='paid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
    ]
