# Generated by Django 3.1 on 2020-09-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_auto_20200907_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
