# Generated by Django 3.0.7 on 2020-09-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0010_auto_20200907_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_manager',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'Position': 'Manager'}, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
    ]
