# Generated by Django 3.0.8 on 2020-09-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0010_auto_20200907_1142'),
        ('event_management', '0010_auto_20200907_1513'),
    ]

    operations = [
    ]
