# Generated by Django 3.0.7 on 2020-09-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0010_auto_20200907_1513'),
        ('event_management', '0010_auto_20200907_1142'),
    ]

    operations = [
    ]
