# Generated by Django 3.0.3 on 2020-09-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0010_auto_20200907_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
