# Generated by Django 3.0.7 on 2020-09-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0011_auto_20200907_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='employee_id',
            new_name='emp_det_id',
        ),
        migrations.AlterField(
            model_name='dept_employee',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Employee'}, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_manager',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_supervisor',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Supervisor'}, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10),
        ),
    ]
