# Generated by Django 3.0.3 on 2020-09-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0011_auto_20200908_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pay_id',
        ),
    ]
