# Generated by Django 3.0.8 on 2020-09-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0011_merge_20200908_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule_file',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
