# Generated by Django 3.0.7 on 2020-09-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0012_auto_20200908_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_details',
            name='trained',
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='permenent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='salary',
            name='paid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
        ),
    ]
