# Generated by Django 3.0.3 on 2020-09-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0012_auto_20200908_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
