# Generated by Django 3.0.8 on 2020-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0012_auto_20200908_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
