# Generated by Django 3.0.7 on 2020-09-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0013_auto_20200908_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_manager_name',
            field=models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_employee',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_manager',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='dept_supervisor',
            name='emp_id',
            field=models.OneToOneField(limit_choices_to={'position': 'Supervisor'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='dept_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.department'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='emp_det_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='dept_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.department'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='emp_det_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
    ]
