# Generated by Django 3.0.3 on 2020-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0013_auto_20200908_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertistment',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='advertistment',
            name='cus_id',
        ),
        migrations.RemoveField(
            model_name='advertistment',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='advertistment',
            name='pack_id',
        ),
        migrations.RemoveField(
            model_name='advertistment',
            name='pay_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
