# Generated by Django 3.0.7 on 2020-10-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0010_auto_20201010_1853'),
        ('event_management', '0014_auto_20200908_0945'),
    ]

    operations = [
    ]
