# Generated by Django 3.0.8 on 2020-10-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0014_auto_20200908_0945'),
        ('event_management', '0011_merge_20200908_1558'),
        ('event_management', '0010_auto_20201010_1853'),
    ]

    operations = [
    ]
