# Generated by Django 3.0.7 on 2020-10-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0015_merge_20201010_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='emp_det_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.emp_details'),
        ),
    ]
