# Generated by Django 3.0.8 on 2020-10-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0015_merge_20201013_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='year',
            new_name='Year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='event',
            name='created_month',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='paid',
            field=models.BooleanField(),
        ),
    ]
