# Generated by Django 3.0.8 on 2020-10-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0017_auto_20201013_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_month',
            field=models.CharField(default='October', max_length=5),
        ),
    ]
