# Generated by Django 3.1 on 2020-10-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0019_auto_20201016_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
