# Generated by Django 3.1 on 2020-10-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0020_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_items',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='event_management.equipment_event'),
        ),
    ]
