# Generated by Django 3.0.8 on 2020-10-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0020_auto_20201017_0258'),
        ('event_management', '0019_event_created_date'),
    ]

    operations = [
    ]
