# Generated by Django 3.1 on 2020-10-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0021_auto_20201016_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='rental_details',
            fields=[
                ('rent_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rental_date', models.DateField(auto_now=True)),
                ('rental_period', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField()),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.payment')),
            ],
        ),
    ]
