# Generated by Django 3.1 on 2020-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0021_auto_20201017_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
