# Generated by Django 3.0.8 on 2020-10-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0021_merge_20201017_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.CharField(default='2020-10-17 07:05:17', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_management.event'),
        ),
    ]
