# Generated by Django 3.0.8 on 2020-10-18 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0022_auto_20201017_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='userActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('createdDate', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2020, 10, 18, 14, 50, 1, 460724), max_length=20),
        ),
    ]
