# Generated by Django 3.0.8 on 2020-10-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0023_auto_20201018_1450'),
        ('event_management', '0022_auto_20201019_0053'),
    ]

    operations = [
    ]
